version: '3'

services:
  postgres:
    image: 'postgres:16'
    container_name: task-flow-DB
    environment:
      - POSTGRES_DB=taskDB
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=root

  app:
    build: ./
    container_name: task-flow-app-java
    ports:
      - "8080:8080"